[App]
Name = "ai.h2o.h2o_aml"
Version = "1.0.0"
Title = "H2O AutoML"
Description = "AutoML using H2O-3"
Category = "Data Science"
tags = ["MACHINE_LEARNING"]
LongDescription = "about.md"

[Runtime]
Module = "src.app"
